export const SELECT_CARD = 'SELECT_CARD';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const FETCH_NEW_SHORTS = 'FETCH_NEW_SHORTS';
export const FETCH_NEW_SHORTS_ERR = 'FETCH_NEW_SHORTS_ERR';
export const NEW_SHORTS_UPDATE = 'NEW_SHORTS_UPDATE';
export const AUTHONTICATION_SUCCESS = 'AUTHONTICATION_SUCCESS';
